Name: api
Host: 0.0.0.0
CpuThreshold: 0
Timeout: 1000000
MaxBytes: 1000000000
Port: 7777
NodeID: 1
Log:
  Encoding: plain
CacheRedis:
  - Host: 172.19.0.5:6379
    Pass:
    Type: node
Rej:
  AccessSecret: ad879037-c7a4-4063-9236-6bfc35d54b7d
  AccessExpire: 600     #过期时间单位秒
OpenAuth:
  Users:
    - UserName: nodeRed
      Password: iThings
    - UserName: root
      Password: iThings
DdEnable: true
SysRpc:
  Enable: true
  Mode: direct
  Conf:
    Etcd:
      Hosts:
        - 172.19.0.3:2379
      Key: sys.rpc
DiRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000