Name: dd
Host: 0.0.0.0
Port: 8848
Log:
  Encoding: plain
DevLink:
  Mode: mqtt
  SubMode: emq
  Mqtt:
    ClientID: dd.rpc
    Pass: iThings
    User: ddsvr
    Brokers:
      - tcp://10.1.0.237:1883
Event:
  Mode: nats
  Nats:
    Url: nats://10.1.0.237:4222