Name: dg.rpc
ListenOn: 0.0.0.0:6166
Log:
  Encoding: plain
DevLink:
  Mode: mqtt
  SubMode: emq
  Mqtt:
    ClientID: dd.rpc
    Pass: iThings
    User: ddsvr
    Brokers:
      - tcp://emqx:1883
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
Event:
  
  Nats:
    Url: nats://nats:4222