#设备交互模块配置-disvr
Name: di.rpc
ListenOn: 127.0.0.1:8180
CpuThreshold: 0
Timeout: 1000000
CacheRedis:
  - Host: 172.19.0.5:6379
    Pass:
    Type: node
Log:
  Encoding: plain
Database:
  DBType: mysql
  DSN: root:password@tcp(172.19.0.4:3306)/iThings?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
TDengine:
  DataSource: root:taosdata@http(172.19.0.6:6041)/iThings?readBufferSize=52428800
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
Event:
  Nats:
    Url: nats://172.19.0.2:4222