Name: dm.rpc
ListenOn: 127.0.0.1:9081
CpuThreshold: 0
Timeout: 1000000
Log:
  Encoding: plain
Etcd:
  Hosts:
    - 172.19.0.3:2379
  Key: dm.rpc
Mysql:
  DataSource: root:password@tcp(172.19.0.4:3306)/iThings?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: 172.19.0.5:6379
    Pass:
    Type: node
TDengine:
  DataSource: root:taosdata@http(172.19.0.6:6041)/iThings?readBufferSize=52428800
AuthWhite:
  Users:
    - UserName: ddsvr
      Password: iThings
  IpRange:
    - 127.0.0.1
    - 172.18.0.1
    - 172.19.0.1
    - 192.168.1.1

