#设备管理模块配置-dmsvr
Name: dm.rpc
ListenOn: 127.0.0.1:9081
CpuThreshold: 0
Timeout: 1000000
Log:
  Encoding: plain
Database:
  DBType: mysql
  DSN: root:password@tcp(mariadb:3306)/iThings?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node
TSDB:
  Driver: taosRestful
  DSN: root:taosdata@http(tdengine:6041)/ithings?readBufferSize=52428800
AuthWhite:
  Users:
    - UserName: ddsvr
      Password: iThings
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: minio:9000
  CustomHost: /api/v1/oss
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false
Event:
  Mode: natsJs
  Nats:
    Url: nats://nats:4222
TimedJobRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000