Name: rule.rpc
ListenOn: 127.0.0.1:9980
Database:
  DBType: mysql
  DSN: root:password@tcp(mariadb:3306)/iThings?charset=utf8mb4&collation=utf8mb4_bin&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000

Event:
  Nats:
    Url: nats://nats:4222