version: '3.2'
# Network
networks:
  ithings_net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
    driver: bridge
services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - "/opt/things/conf/nats/nats-server.conf:/nats-server.conf"
    networks:
      ithings_net:
        aliases:
          - node1.nats.io
  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd-v3
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL_API: 3
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
    networks:
      ithings_net:
        aliases:
          - node1.etcd.io
  mysql-db:
    container_name: mysql-docker        # 指定容器的名称
    image: mysql:5.7              # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai     # 指定时区
    working_dir: /mysql/
    volumes:
      - "/opt/things/conf/mysql/:/mysql/"
      - "/var/mysql/data:/var/lib/mysql"           # 挂载数据目录
      - "/var/mysql/config:/etc/mysql/conf.d"      # 挂载配置文件目录
    networks:
      ithings_net:
        aliases:
          - node1.mysql.io
  redis:
    hostname: redis
    image: redis
    container_name: redis
    restart: always
    command: redis-server /etc/redis.conf # 启动redis命令
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis.conf
    ports:
      - "6379:6379"
    networks:
      ithings_net:
        aliases:
          - node1.redis.io
  tdengine:
    image: tdengine/tdengine
    container_name: tdengine
    hostname: tdengine
    ports:
      - "6030:6030"
      - "6035:6035"
      - "6041:6041"
      - "6030-6040:6030-6040/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/volume/tdengine/lib:/var/lib/taos:Z
      - /data/volume/tdengine/log:/var/log/taos:Z
    restart: always
    tty: true
    networks:
      ithings_net:
        aliases:
          - node1.tdengine.io

  # Emqx
  emqx:
    container_name: emqx
    image:  emqx/emqx
    hostname: node1.emqx.io
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - "/opt/things/conf/emqx/etc/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf"
      - "/opt/things/conf/emqx/data/loaded_plugins:/opt/emqx/data/loaded_plugins"
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
    networks:
      ithings_net:
        aliases:
          - node1.emqx.io

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: password #大于等于8位
    logging:
      options:
        max-size: "50M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes:
      - /opt/things/data/minio/data:/data # 映射文件路径