version: '3.2'
# Network
networks:
  ithings_net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
    driver: bridge

services:
  ithings:
    image: ithings/ithings:latest
    container_name: ithings
    ports:
      - "7777:7777"
    volumes:
      - ./deploy/conf/ithings/apisvr/etc:/ithings/etc
