version: '3.2'
# Network
networks:
  ithings_net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
    driver: bridge

services:
  nats-server:
    image: nats:2.8-alpine
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./deploy/conf/nats/nats-server.conf:/nats-server.conf
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.nats.io

  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd-v3
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL_API: 3
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
    volumes:
      - ${DATA_DIR}/data/etcd/data:/etcd-data
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.etcd.io

  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai
    volumes:
      - ./deploy/conf/mysql/sql:/mysql
      - ${DATA_DIR}/data/mariadb/:/var/lib/mysql
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.mysql.io

  redis:
    hostname: redis
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.redis.io

  tdengine:
    image: tdengine/tdengine
    container_name: tdengine
    hostname: tdengine
    ports:
      - "6030:6030"
      - "6035:6035"
      - "6041:6041"
      - "6030-6040:6030-6040/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATA_DIR}/data/tdengine/lib:/var/lib/taos:Z
      - ${DATA_DIR}/data/tdengine/log:/var/log/taos:Z
    restart: always
    tty: true
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.tdengine.io

  emqx:
    container_name: emqx
    image: emqx/emqx
    hostname: node1.emqx.io
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - ./deploy/conf/emqx/etc/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./deploy/conf/emqx/data/loaded_plugins:/opt/emqx/data/loaded_plugins
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        aliases:
          - node1.emqx.io

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: password
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    volumes:
      - ${DATA_DIR}/data/minio/data:/data
